### ISSUE TITLE
code missing

### ISSUE THREAD

**Issue by learningjs42** [PacktPublishing/Real-World-Projects-with-MEAN-Stack#1]
the jwt code is missing there is no 4.04 need to be added

**Comment by abhi-govula** [comment]
Added the missing code [here](https://github.com/PacktPublishing/Real-World-Projects-with-MEAN-Stack/commit/8dcebfbe714333b683f43097c694a43812c10f96)

**Comment by learningjs42** [comment]
thanks abhi :) your a great teacher !!!
